### ISSUE TITLE
Update to tabs

### ISSUE THREAD

**Issue by maclean** [ncareol/django-ncharts#61]
Perhaps we don't want tabs if there are less than (say) 10 variables?

Can we add a "clear all" and "set all" that applies only to each tab pane?

**Comment by maclean** [comment]
The first variable that should be in each tab is missing. For example, there should be an ADIFR in the aircraft variables.  The code probably checks its first letter and then doesn't use it?

**Comment by nguyenduchien1994** [comment]
I still see the first variable in each tab and I test it as well. Can you check it again ?

**Comment by maclean** [comment]
The next step is to write a function in python, called by the view get/post method, to create a dictionary of variables by their tab name. Seems that it should be method in the Dataaset class, since it should know the dataset type. The tabs will be different for different types of datasets. For example an "aircraft" type and an "isfs" type.

This tab dict is then passed in the context to the dataset.html template, which will iterate of it to create the tabs.

**Comment by maclean** [comment]
Now just have to write a function to create categories of ISFS variables. Perhaps a function for the aircraft too?

**Comment by maclean** [comment]
If a platform for a dataset is ISFS, look at the field before the first (optional) dot.
Number of single quote marks:

0:
   T, RH, P, Spd, Dir, U, V:  tab="met", tab tooltip="Meteorological variables"
   Rnet, Rsw, Rlw, Rpile, Rpar, Tcase, Tdome: tab="rad", tooltip="Radiation"
  Tsoil, dTsoil_dt, Qsoil, Gsoil, Vheat, Vpile, Tau63, Lambdasoil: tab="soil", tooltip="Soil variables"
  
  u,v,w,ldiag, diagbits: tab="3dWind", tooltip=3D wind variables"
  tc,t, h2o,co2,kh2o, o3, q, mr: tab="scalars", tooltip="fast scalars"

1: shouldn't happen
2: tab="2ndMoments"
3: tab="3rdMoments"
4: tab="4thMoments"

**Comment by maclean** [comment]
Looks good.  TODO: add some order to the tabs. Put moments last

**Comment by maclean** [comment]
Done. Tabs will be displayed in a consistent order.
